name: delivery_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  # mapbox_maps_flutter: ^1.0.0  # Comentado temporalmente
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  permission_handler: ^12.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/all.png
    - assets/images/icons/despensa.png
    - assets/images/icons/food.png
    - assets/images/icons/panadero.png
    - assets/images/icons/verduras.png
    - assets/images/businesses/business_belleza_natural.jpg
    - assets/images/businesses/business_boutique_alma.jpg
    - assets/images/businesses/business_fruteria_la_cosecha.jpg
    - assets/images/businesses/business_hogar_deco.jpg
    - assets/images/businesses/business_joyas_brillantes.jpg
    - assets/images/businesses/business_panaderia_el_amanecer.jpg
    - assets/images/businesses/business_restaurante_dona_maria.jpg
    - assets/images/businesses/business_tecnomundo.jpeg
    - assets/images/businesses/panaderia.jpg
    - assets/images/businesses/panaderia02.jpg
    - assets/images/ui/eletronicos.jpg
