name: delivery_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  # mapbox_maps_flutter: ^1.0.0  # Comentado temporalmente
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  permission_handler: ^12.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/businesses/
    - assets/images/products/
    - assets/images/categories/
    - assets/images/ui/
    - assets/images/backgrounds/