// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-dcsAHoET-rg21-C-T0qQIaoxLYqgFTA',
    appId: '1:397640943349:android:46f26f58525316e2a5a7bc',
    messagingSenderId: '397640943349',
    projectId: 'delivery-app-15f53',
    storageBucket: 'delivery-app-15f53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-dcsAHoET-rg21-C-T0qQIaoxLYqgFTA',
    appId: '1:397640943349:ios:46f26f58525316e2a5a7bc',
    messagingSenderId: '397640943349',
    projectId: 'delivery-app-15f53',
    storageBucket: 'delivery-app-15f53.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-dcsAHoET-rg21-C-T0qQIaoxLYqgFTA',
    appId: '1:397640943349:web:46f26f58525316e2a5a7bc',
    messagingSenderId: '397640943349',
    projectId: 'delivery-app-15f53',
    authDomain: 'delivery-app-15f53.firebaseapp.com',
    storageBucket: 'delivery-app-15f53.firebasestorage.app',
  );
}
